// Hand-curated. Rule: shown only the pic, a five-year-old says exactly this word.
// Tier 1: short CVC / common letters. Tier 2: blends and ck/ll/ss. Tier 3: vowel
// digraphs, magic-e, sh/th/ng, r-controlled vowels.
//
// `pic` is one of:
//   { kind: 'emoji', text }  - a single emoji glyph, rendered as text
//   { kind: 'svg', src }     - an image at `img/<name>.svg` or `.png`, relative to this file
//   { kind: 'colour', css }  - a solid colour swatch, `css` a `#rrggbb` string
// `noA` marks a word whose picture a grown-up would not preface with "a" (e.g.
// "ice", numbers) so sentence frames can skip the article.
export const WORDS = [
  // tier 1
  { w: 'cat', tier: 1, pic: { kind: 'emoji', text: '🐱' } },
  { w: 'dog', tier: 1, pic: { kind: 'emoji', text: '🐶' } },
  { w: 'sun', tier: 1, pic: { kind: 'emoji', text: '☀️' } },
  { w: 'bed', tier: 1, pic: { kind: 'emoji', text: '🛏️' } },
  { w: 'pig', tier: 1, pic: { kind: 'emoji', text: '🐷' } },
  { w: 'bus', tier: 1, pic: { kind: 'emoji', text: '🚌' } },
  { w: 'egg', tier: 1, pic: { kind: 'emoji', text: '🥚' } },
  { w: 'hat', tier: 1, pic: { kind: 'emoji', text: '🎩' } },
  { w: 'cow', tier: 1, pic: { kind: 'emoji', text: '🐮' } },
  { w: 'bee', tier: 1, pic: { kind: 'emoji', text: '🐝' } },
  { w: 'ant', tier: 1, pic: { kind: 'emoji', text: '🐜' } },
  { w: 'fox', tier: 1, pic: { kind: 'emoji', text: '🦊' } },
  { w: 'bat', tier: 1, pic: { kind: 'emoji', text: '🦇' } },
  { w: 'car', tier: 1, pic: { kind: 'emoji', text: '🚗' } },
  { w: 'key', tier: 1, pic: { kind: 'emoji', text: '🔑' } },
  { w: 'box', tier: 1, pic: { kind: 'emoji', text: '📦' } },
  { w: 'pen', tier: 1, pic: { kind: 'emoji', text: '🖊️' } },
  { w: 'bag', tier: 1, pic: { kind: 'emoji', text: '👜' } },
  { w: 'cap', tier: 1, pic: { kind: 'emoji', text: '🧢' } },
  { w: 'owl', tier: 1, pic: { kind: 'emoji', text: '🦉' } },
  { w: 'pie', tier: 1, pic: { kind: 'emoji', text: '🥧' } },
  { w: 'eye', tier: 1, pic: { kind: 'emoji', text: '👁️' } },
  { w: 'ear', tier: 1, pic: { kind: 'emoji', text: '👂' } },
  { w: 'leg', tier: 1, pic: { kind: 'emoji', text: '🦵' } },
  { w: 'log', tier: 1, pic: { kind: 'emoji', text: '🪵' } },
  { w: 'web', tier: 1, pic: { kind: 'emoji', text: '🕸️' } },
  { w: 'saw', tier: 1, pic: { kind: 'emoji', text: '🪚' } },
  { w: 'axe', tier: 1, pic: { kind: 'emoji', text: '🪓' } },
  { w: 'pin', tier: 1, pic: { kind: 'emoji', text: '📌' } },
  { w: 'map', tier: 1, pic: { kind: 'emoji', text: '🗺️' } },
  { w: 'ice', tier: 1, pic: { kind: 'emoji', text: '🧊' }, noA: true },
  { w: 'one', tier: 1, pic: { kind: 'emoji', text: '1️⃣' }, noA: true },
  { w: 'two', tier: 1, pic: { kind: 'emoji', text: '2️⃣' }, noA: true },
  { w: 'six', tier: 1, pic: { kind: 'emoji', text: '6️⃣' }, noA: true },
  { w: 'ten', tier: 1, pic: { kind: 'emoji', text: '🔟' }, noA: true },
  // colours: shown as a solid tile, never an image
  { w: 'red',  tier: 1, pic: { kind: 'colour', css: '#e53935' }, pos: 'adj', noA: true },
  { w: 'blue', tier: 2, pic: { kind: 'colour', css: '#1e88e5' }, pos: 'adj', noA: true },
  { w: 'pink', tier: 2, pic: { kind: 'colour', css: '#f06292' }, pos: 'adj', noA: true },
  { w: 'grey', tier: 3, pic: { kind: 'colour', css: '#9e9e9e' }, pos: 'adj', noA: true },
  // tier 2
  { w: 'frog', tier: 2, pic: { kind: 'emoji', text: '🐸' } },
  { w: 'milk', tier: 2, pic: { kind: 'emoji', text: '🥛' }, noA: true },
  { w: 'duck', tier: 2, pic: { kind: 'emoji', text: '🦆' } },
  { w: 'bell', tier: 2, pic: { kind: 'emoji', text: '🔔' } },
  { w: 'ball', tier: 2, pic: { kind: 'emoji', text: '⚽' } },
  { w: 'drum', tier: 2, pic: { kind: 'emoji', text: '🥁' } },
  { w: 'crab', tier: 2, pic: { kind: 'emoji', text: '🦀' } },
  { w: 'hand', tier: 2, pic: { kind: 'emoji', text: '✋' } },
  { w: 'sock', tier: 2, pic: { kind: 'emoji', text: '🧦' } },
  { w: 'tent', tier: 2, pic: { kind: 'emoji', text: '⛺' } },
  { w: 'flag', tier: 2, pic: { kind: 'emoji', text: '🚩' } },
  { w: 'corn', tier: 2, pic: { kind: 'emoji', text: '🌽' }, noA: true },
  { w: 'wolf', tier: 2, pic: { kind: 'emoji', text: '🐺' } },
  { w: 'bath', tier: 2, pic: { kind: 'emoji', text: '🛁' } },
  { w: 'fish', tier: 2, pic: { kind: 'emoji', text: '🐟' } },
  { w: 'ship', tier: 2, pic: { kind: 'emoji', text: '🚢' } },
  { w: 'shoe', tier: 2, pic: { kind: 'emoji', text: '👟' } },
  { w: 'ring', tier: 2, pic: { kind: 'emoji', text: '💍' } },
  { w: 'worm', tier: 2, pic: { kind: 'emoji', text: '🪱' } },
  { w: 'bird', tier: 2, pic: { kind: 'emoji', text: '🐦' } },
  { w: 'star', tier: 2, pic: { kind: 'emoji', text: '⭐' } },
  { w: 'fire', tier: 2, pic: { kind: 'emoji', text: '🔥' }, noA: true },
  { w: 'four', tier: 2, pic: { kind: 'emoji', text: '4️⃣' }, noA: true },
  { w: 'five', tier: 2, pic: { kind: 'emoji', text: '5️⃣' }, noA: true },
  { w: 'nine', tier: 2, pic: { kind: 'emoji', text: '9️⃣' }, noA: true },
  // tier 3
  { w: 'cake', tier: 3, pic: { kind: 'emoji', text: '🍰' } },
  { w: 'tree', tier: 3, pic: { kind: 'emoji', text: '🌳' } },
  { w: 'boat', tier: 3, pic: { kind: 'emoji', text: '⛵' } },
  { w: 'bear', tier: 3, pic: { kind: 'emoji', text: '🐻' } },
  { w: 'lion', tier: 3, pic: { kind: 'emoji', text: '🦁' } },
  { w: 'rain', tier: 3, pic: { kind: 'emoji', text: '🌧️' }, noA: true },
  { w: 'leaf', tier: 3, pic: { kind: 'emoji', text: '🍃' } },
  { w: 'foot', tier: 3, pic: { kind: 'emoji', text: '🦶' } },
  { w: 'nose', tier: 3, pic: { kind: 'emoji', text: '👃' } },
  { w: 'door', tier: 3, pic: { kind: 'emoji', text: '🚪' } },
  { w: 'bone', tier: 3, pic: { kind: 'emoji', text: '🦴' } },
  { w: 'rose', tier: 3, pic: { kind: 'emoji', text: '🌹' } },
  { w: 'kite', tier: 3, pic: { kind: 'emoji', text: '🪁' } },
  { w: 'bike', tier: 3, pic: { kind: 'emoji', text: '🚲' } },
  { w: 'moon', tier: 3, pic: { kind: 'emoji', text: '🌙' } },
  { w: 'book', tier: 3, pic: { kind: 'emoji', text: '📖' } },
  { w: 'goat', tier: 3, pic: { kind: 'emoji', text: '🐐' } },
  { w: 'deer', tier: 3, pic: { kind: 'emoji', text: '🦌' } },
  { w: 'seal', tier: 3, pic: { kind: 'emoji', text: '🦭' } },
  { w: 'pear', tier: 3, pic: { kind: 'emoji', text: '🍐' } },
  { w: 'rice', tier: 3, pic: { kind: 'emoji', text: '🍚' }, noA: true },
  { w: 'coin', tier: 3, pic: { kind: 'emoji', text: '🪙' } },
  { w: 'dice', tier: 3, pic: { kind: 'emoji', text: '🎲' } },
  { w: 'wand', tier: 3, pic: { kind: 'emoji', text: '🪄' } },
  { w: 'fork', tier: 3, pic: { kind: 'emoji', text: '🍴' } },
  { w: 'hook', tier: 3, pic: { kind: 'emoji', text: '🪝' } },
  { w: 'bowl', tier: 3, pic: { kind: 'emoji', text: '🥣' } },
];

// Frames: `{noun}` is the pictured word's slot (any part of speech named by `pos`, default noun);
// `{sight}` is an optional sight-word slot and `fits` lists EVERY sight word that makes the sentence right.
export const FRAMES = [
  { text: 'I {sight} the {noun}',   fits: ['like', 'see', 'have'] },
  { text: 'We {sight} the {noun}',  fits: ['like', 'see', 'have'] },
  { text: '{sight} is a {noun}',    fits: ['here', 'this', 'it'] },
  { text: 'The {noun} is {sight}',  fits: ['here', 'up', 'in'] },
  { text: 'I like {sight} {noun}',  fits: ['my', 'the', 'this'] },
  { text: 'Here is {sight} {noun}', fits: ['my', 'the', 'this'] },
  { text: 'The {noun} {sight} here', fits: ['is', 'was'] },
  { text: 'I can see a {noun}',     fits: [] },
  { text: 'Look at the {noun}',     fits: [] },
  { text: 'I can {noun}',           fits: [], pos: 'verb' },
  { text: 'We {sight} {noun}',      fits: ['can'], pos: 'verb' },
  { text: 'Look at me {noun}',      fits: [], pos: 'verb' },
  { text: 'It is {noun}',           fits: [], pos: 'adj' },
  { text: '{sight} is {noun}',      fits: ['it', 'this'], pos: 'adj' },
];
