[package]
name = "smelt-optimizer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
smelt-parser = { path = "../smelt-parser" }
rowan = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
pyo3 = { workspace = true, optional = true }

[features]
python = ["pyo3"]
