//! Drift gate for the generated web-analytics maintenance tutorial page
//! (`docs/plans/20260710-web-analytics-maintenance-demo.md` Phase 8).
//!
//! Oracle: `docs-site/docs/examples/web-analytics-maintenance.md` is
//! generated by `examples/web_analytics/generate_tutorial.py` from real
//! `smelt explain --show-sql --json` / `smelt backbuild --dry-run` output
//! against `examples/web_analytics/` — never hand-pasted. This test
//! re-derives the same output independently (its own Rust rendering, not a
//! call into the Python generator) via the compiled `smelt` binary and
//! asserts every `<!-- smelt-generate: ... -->`-marked fenced block in the
//! committed page byte-matches a fresh derivation. Cheap: `explain
//! --show-sql` never connects to a backend, and `backbuild --dry-run`
//! writes nothing to the (temp, per-test) database file it opens — no
//! datagen, no real query execution. Runs in plain `cargo test`.

use std::path::{Path, PathBuf};
use std::process::Command;

/// One `<!-- smelt-generate: <command> -->` marker plus the fenced block
/// that immediately follows it, as found in the committed page.
struct GeneratedBlock {
    /// The full argv tail after `smelt` (e.g. `["explain",
    /// "silver.events_parsed", "--show-sql", "--json", "--period", "..."]`).
    args: Vec<String>,
    /// The fenced block's inner content (no fence lines), as committed.
    committed: String,
}

/// Parse every `<!-- smelt-generate: ... -->` marker + following fenced
/// code block out of the page. Panics (via the test's own assertions) only
/// on a structurally malformed page; a page with zero markers still parses
/// to an empty list so the "at least one of each kind" assertions below
/// give a clear failure instead of an opaque parse panic.
fn parse_generated_blocks(page: &str) -> Vec<GeneratedBlock> {
    let lines: Vec<&str> = page.lines().collect();
    let mut blocks = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if let Some(rest) = line
            .strip_prefix("<!-- smelt-generate: ")
            .and_then(|s| s.strip_suffix(" -->"))
        {
            let args: Vec<String> = rest.split_whitespace().map(|s| s.to_string()).collect();
            // Scan forward for the opening fence.
            let mut j = i + 1;
            while j < lines.len() && !lines[j].trim_start().starts_with("```") {
                j += 1;
            }
            assert!(
                j < lines.len(),
                "marker '{}' at line {} has no following fenced code block",
                rest,
                i + 1
            );
            let fence_start = j;
            j += 1;
            let content_start = j;
            while j < lines.len() && lines[j].trim() != "```" {
                j += 1;
            }
            assert!(
                j < lines.len(),
                "fenced block opened at line {} (marker '{}') is never closed",
                fence_start + 1,
                rest
            );
            let committed = lines[content_start..j].join("\n");
            blocks.push(GeneratedBlock { args, committed });
            i = j + 1;
        } else {
            i += 1;
        }
    }
    blocks
}

/// Drop comment-placeholder lines that are only `--` once trimmed — a
/// cosmetic artifact of the maintenance-statement emitter (it reserves a
/// blank comment line ahead of each restated source comment). Must match
/// `examples/web_analytics/generate_tutorial.py::canonicalize` exactly.
fn canonicalize(text: &str) -> String {
    text.lines()
        .filter(|l| l.trim() != "--")
        .collect::<Vec<_>>()
        .join("\n")
        .trim_matches('\n')
        .to_string()
}

/// Build the same compact per-cell SQL block
/// `generate_tutorial.py::render_cells_sql` builds from an `explain
/// --show-sql --json` `cells` array.
fn render_cells_sql(cells: &[serde_json::Value]) -> String {
    let mut blocks = Vec::new();
    for cell in cells {
        let trigger = cell["trigger"].as_str().expect("cell.trigger is a string");
        let statements = cell["statements"].as_array().cloned().unwrap_or_default();
        if statements.is_empty() {
            if let Some(reason) = cell.get("no_statements_reason").and_then(|r| r.as_str()) {
                blocks.push(format!(
                    "-- trigger: {trigger}\n-- (no statements: {reason})"
                ));
            }
            continue;
        }

        let mut lines = vec![format!("-- trigger: {trigger}")];
        // Group consecutive statements sharing a transactional_group.
        let mut groups: Vec<(i64, Vec<String>)> = Vec::new();
        for stmt in &statements {
            let gid = stmt["transactional_group"]
                .as_i64()
                .expect("statement.transactional_group is an integer");
            let sql = stmt["sql"]
                .as_str()
                .expect("statement.sql is a string")
                .to_string();
            if let Some(last) = groups.last_mut() {
                if last.0 == gid {
                    last.1.push(sql);
                    continue;
                }
            }
            groups.push((gid, vec![sql]));
        }

        for (_gid, sqls) in groups {
            if sqls.len() > 1 {
                lines.push("BEGIN".to_string());
                for sql in &sqls {
                    for sql_line in sql.split('\n') {
                        if sql_line.is_empty() {
                            lines.push(String::new());
                        } else {
                            lines.push(format!("  {sql_line}"));
                        }
                    }
                }
                lines.push("COMMIT".to_string());
            } else {
                lines.push(sqls[0].clone());
            }
        }
        blocks.push(lines.join("\n"));
    }
    blocks.join("\n\n")
}

fn web_analytics_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples/web_analytics")
        .canonicalize()
        .expect("examples/web_analytics exists")
}

fn tutorial_page_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../docs-site/docs/examples/web-analytics-maintenance.md")
}

/// Re-derive an `explain --show-sql --json` block's expected content by
/// spawning the real `smelt` binary (no backend connection — `--show-sql`
/// never opens one) and rendering it the same way the generator does.
fn fresh_explain_block(args: &[String], project_dir: &Path) -> String {
    let output = Command::new(env!("CARGO_BIN_EXE_smelt"))
        .args(args)
        .current_dir(project_dir)
        .output()
        .unwrap_or_else(|e| panic!("spawn smelt {}: {e}", args.join(" ")));
    assert!(
        output.status.success(),
        "smelt {} failed: stderr={}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    let data: serde_json::Value = serde_json::from_str(&stdout).unwrap_or_else(|e| {
        panic!(
            "smelt {} did not print valid JSON: {e}\n{stdout}",
            args.join(" ")
        )
    });
    let cells = data["cells"].as_array().unwrap_or_else(|| {
        panic!(
            "smelt {} JSON has no 'cells' array: {stdout}",
            args.join(" ")
        )
    });
    canonicalize(&render_cells_sql(cells))
}

/// Re-derive a `backbuild --dry-run` block's expected content by spawning
/// the real `smelt` binary against a private temp database file (dry-run
/// prints only — it never queries or writes real data, but a distinct
/// per-test path avoids any file contention with other tests touching the
/// same example project).
fn fresh_backbuild_block(args: &[String], project_dir: &Path, db_path: &Path) -> String {
    let mut full_args = args.to_vec();
    full_args.push("--database".to_string());
    full_args.push(db_path.to_string_lossy().into_owned());

    let output = Command::new(env!("CARGO_BIN_EXE_smelt"))
        .args(&full_args)
        .current_dir(project_dir)
        .output()
        .unwrap_or_else(|e| panic!("spawn smelt {}: {e}", full_args.join(" ")));
    assert!(
        output.status.success(),
        "smelt {} failed: stderr={}",
        full_args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    canonicalize(&String::from_utf8_lossy(&output.stdout))
}

#[test]
fn web_analytics_maintenance_tutorial_sql_is_fresh() {
    let page_path = tutorial_page_path();
    let page = std::fs::read_to_string(&page_path).unwrap_or_else(|e| {
        panic!(
            "failed to read {}: {e} — run `python3 examples/web_analytics/generate_tutorial.py` \
             to generate it",
            page_path.display()
        )
    });

    let blocks = parse_generated_blocks(&page);
    assert!(
        !blocks.is_empty(),
        "expected at least one <!-- smelt-generate: ... --> block in {}",
        page_path.display()
    );

    let project_dir = web_analytics_dir();
    let tmp = tempfile::TempDir::new().expect("create tempdir for backbuild --database");
    let db_path = tmp.path().join("freshness.duckdb");

    let mut found_explain = false;
    let mut found_backbuild = false;
    // The cross-midnight derived-output-window section: a single-day
    // `silver.sessions` explain block pinned to the day-46 shape (an event
    // at 2026-05-04 00:03 extending a session rooted 2026-05-03 23:47). Its
    // period argument distinguishes it from the earlier generic sessions
    // block (`EXPLAIN_PERIOD`, 2026-04-10..2026-04-11) in the same page.
    let mut found_cross_midnight_sessions = false;

    for block in &blocks {
        let subcommand = block
            .args
            .first()
            .unwrap_or_else(|| panic!("empty smelt-generate marker command"));

        let fresh = match subcommand.as_str() {
            "explain" => {
                found_explain = true;
                fresh_explain_block(&block.args, &project_dir)
            }
            "backbuild" => {
                found_backbuild = true;
                fresh_backbuild_block(&block.args, &project_dir, &db_path)
            }
            other => panic!(
                "unrecognized smelt-generate subcommand '{other}' in marker: {}",
                block.args.join(" ")
            ),
        };

        if block.args.first().map(String::as_str) == Some("explain")
            && block.args.iter().any(|a| a == "silver.sessions")
            && block.args.iter().any(|a| a.contains("2026-05-04"))
        {
            found_cross_midnight_sessions = true;
        }

        assert_eq!(
            fresh,
            block.committed,
            "committed fenced block for `smelt {}` has drifted from a fresh re-derivation — \
             run `python3 examples/web_analytics/generate_tutorial.py` to regenerate \
             {}",
            block.args.join(" "),
            page_path.display()
        );
    }

    assert!(
        found_explain,
        "expected at least one 'explain' smelt-generate block in {}",
        page_path.display()
    );
    assert!(
        found_backbuild,
        "expected at least one 'backbuild' smelt-generate block in {}",
        page_path.display()
    );
    assert!(
        found_cross_midnight_sessions,
        "expected a `silver.sessions` explain block pinned to the cross-midnight \
         day-46 period (2026-05-04..2026-05-05) demonstrating the derived output \
         window's skew inversion in {}",
        page_path.display()
    );

    // Two-boundary truncation subsection: prose-only (no `smelt-generate`
    // block — `examples/web_analytics`' datagen fixture never produces a
    // session long enough to realise this shape). The numbers quoted in
    // prose come from the injected 60-event chain the real pipeline is run
    // over in `per_partition_equivalence.rs::web_analytics_session_attribution_matches_full_rebuild`
    // (mirrored by
    // `cross_midnight_rebase.rs::two_boundary_session_truncated_at_declared_bound`);
    // freshness for this subsection is guaranteed by those tests asserting
    // the exact pinned values, not by re-deriving a fenced block here — so
    // this gate only checks the subsection exists and quotes them.
    assert!(
        page.contains("What about a session that spans two midnights?"),
        "expected the two-boundary-truncation subsection ('What about a \
         session that spans two midnights?') in {} — run \
         `python3 examples/web_analytics/generate_tutorial.py` to regenerate \
         it",
        page_path.display()
    );
    for pinned in ["event_count=58", "session_end=2026-03-20 23:30"] {
        assert!(
            page.contains(pinned),
            "expected the two-boundary-truncation subsection to quote the \
             pinned truncated-session value '{pinned}' (asserted against the \
             real pipeline in per_partition_equivalence.rs) in {}",
            page_path.display()
        );
    }
}
