//! Drift gate for the generated web-analytics tutorial series.
//!
//! Oracle: every page under `docs-site/docs/examples/web-analytics/*.md` is
//! generated by `examples/web_analytics/generate_tutorial.py` from its
//! matching template in `examples/web_analytics/tutorial_pages/*.md`. Two
//! directive forms in a template are expanded into a fenced block: a
//! `<!-- smelt-include: <path> -->` embeds a source file (comment-stripped),
//! and a `<!-- smelt-generate: [@opts] <argv...> -->` runs the real `smelt`
//! CLI against a fresh temp copy of a workspace and embeds its (rendered)
//! output — never hand-pasted.
//!
//! This test re-derives every directive's expected content independently
//! (its own Rust rendering, not a call into the Python generator) via the
//! compiled `smelt` binary (`env!("CARGO_BIN_EXE_smelt")`) and the source
//! include files, and asserts a byte-match against the committed pages.
//! Every transform below is a mirror of the matching function in
//! `examples/web_analytics/generate_tutorial.py` — keep them in lockstep;
//! each is annotated with the Python function it must match exactly.
//!
//! Cheap: `explain --show-sql` never connects to a backend, `backbuild
//! --dry-run` writes nothing to the (temp, per-test) database file it
//! opens, and `run --dry-run` / `diff` in this suite never touch real data
//! either — no datagen, no real query execution. Runs in plain `cargo test`.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

// ---------------------------------------------------------------------------
// Shared render-mode transforms. Each must match
// `examples/web_analytics/generate_tutorial.py::<fn>` exactly.
// ---------------------------------------------------------------------------

/// Comment-line prefixes that survive `strip_sql_comments` — structural
/// markers the tutorial prose refers to, not restated source comments.
/// Mirrors `generate_tutorial.py::STRUCTURAL_PREFIXES`.
const STRUCTURAL_PREFIXES: &[&str] = &[
    "-- trigger:",
    "-- chunk",
    "-- (no statements",
    "-- Would run:",
];

/// Names excluded when materializing a temp copy of a workspace directory.
/// `*.duckdb` files are excluded by suffix, handled separately. Mirrors
/// `generate_tutorial.py::EXCLUDE_NAMES`.
const EXCLUDE_NAMES: &[&str] = &[
    "target",
    ".smelt",
    "data",
    "output",
    "generate_tutorial.py",
    "tutorial_pages",
    "tutorial_stages",
    "deployed_schema_fixture",
    "__pycache__",
];

/// Mirrors `generate_tutorial.py::canonicalize`: drop comment-placeholder
/// lines that are only `--` once trimmed, then strip leading/trailing
/// newlines.
fn canonicalize(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').filter(|l| l.trim() != "--").collect();
    lines.join("\n").trim_matches('\n').to_string()
}

/// Mirrors `generate_tutorial.py::_collapse_and_trim`: collapse runs of >1
/// consecutive blank lines to one, then trim leading/trailing blank lines.
fn collapse_and_trim(lines: &[&str]) -> String {
    let mut out: Vec<&str> = Vec::new();
    let mut blank_run = 0;
    for &l in lines {
        if l.trim().is_empty() {
            blank_run += 1;
            if blank_run <= 1 {
                out.push(l);
            }
        } else {
            blank_run = 0;
            out.push(l);
        }
    }
    while out.first().map(|l| l.trim().is_empty()).unwrap_or(false) {
        out.remove(0);
    }
    while out.last().map(|l| l.trim().is_empty()).unwrap_or(false) {
        out.pop();
    }
    out.join("\n")
}

/// Mirrors `generate_tutorial.py::strip_sql_comments`.
fn strip_sql_comments(text: &str) -> String {
    let kept: Vec<&str> = text
        .split('\n')
        .filter(|line| {
            let ls = line.trim_start();
            !ls.starts_with("--") || STRUCTURAL_PREFIXES.iter().any(|p| ls.starts_with(p))
        })
        .collect();
    collapse_and_trim(&kept)
}

/// Mirrors `generate_tutorial.py::render_cells_sql`: build a compact SQL
/// block from an `explain --show-sql --json` `cells` array, one section per
/// cell (labelled by its trigger), statements sharing a
/// `transactional_group` wrapped in `BEGIN`/`COMMIT`.
fn render_cells_sql(cells: &[serde_json::Value]) -> String {
    let mut blocks = Vec::new();
    for cell in cells {
        let trigger = cell["trigger"].as_str().expect("cell.trigger is a string");
        let statements = cell["statements"].as_array().cloned().unwrap_or_default();
        if statements.is_empty() {
            if let Some(reason) = cell.get("no_statements_reason").and_then(|r| r.as_str()) {
                blocks.push(format!(
                    "-- trigger: {trigger}\n-- (no statements: {reason})"
                ));
            }
            continue;
        }

        let mut lines = vec![format!("-- trigger: {trigger}")];
        let mut groups: Vec<(i64, Vec<String>)> = Vec::new();
        for stmt in &statements {
            let gid = stmt["transactional_group"]
                .as_i64()
                .expect("statement.transactional_group is an integer");
            let sql = stmt["sql"]
                .as_str()
                .expect("statement.sql is a string")
                .to_string();
            if let Some(last) = groups.last_mut() {
                if last.0 == gid {
                    last.1.push(sql);
                    continue;
                }
            }
            groups.push((gid, vec![sql]));
        }

        for (_gid, sqls) in groups {
            if sqls.len() > 1 {
                lines.push("BEGIN".to_string());
                for sql in &sqls {
                    for sql_line in sql.split('\n') {
                        if sql_line.is_empty() {
                            lines.push(String::new());
                        } else {
                            lines.push(format!("  {sql_line}"));
                        }
                    }
                }
                lines.push("COMMIT".to_string());
            } else {
                lines.push(sqls[0].clone());
            }
        }
        blocks.push(lines.join("\n"));
    }
    blocks.join("\n\n")
}

/// Mirrors `generate_tutorial.py::_is_skeleton_structural`.
fn is_skeleton_structural(line: &str) -> bool {
    let ls = line.trim_start();
    if ls.is_empty() {
        return true;
    }
    if STRUCTURAL_PREFIXES.iter().any(|p| ls.starts_with(p)) {
        return true;
    }
    if line.trim() == "BEGIN" || line.trim() == "COMMIT" {
        return true;
    }
    if ls.starts_with("DELETE FROM ") {
        return true;
    }
    if ls.starts_with("INSERT INTO ") {
        return true;
    }
    if ls.starts_with(") AS _smelt_output_clamp") || ls.starts_with(") _smelt_typed") {
        return true;
    }
    false
}

/// Mirrors `generate_tutorial.py::skeleton`.
fn skeleton(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut out: Vec<String> = Vec::new();
    let mut i = 0;
    let n = lines.len();
    while i < n {
        if is_skeleton_structural(lines[i]) {
            out.push(lines[i].to_string());
            i += 1;
        } else {
            let l = lines[i];
            let indent_len = l.len() - l.trim_start().len();
            let indent = &l[..indent_len];
            out.push(format!(
                "{indent}-- … model SELECT body (see the full SQL below) …"
            ));
            i += 1;
            while i < n && !is_skeleton_structural(lines[i]) {
                i += 1;
            }
        }
    }
    let refs: Vec<&str> = out.iter().map(String::as_str).collect();
    collapse_and_trim(&refs)
}

/// Mirrors `generate_tutorial.py::render_text`.
fn render_text(raw: &str) -> String {
    let mut lines: Vec<String> = raw.split('\n').map(|l| l.trim_end().to_string()).collect();
    while lines.first().map(|l| l.trim().is_empty()).unwrap_or(false) {
        lines.remove(0);
    }
    while lines.last().map(|l| l.trim().is_empty()).unwrap_or(false) {
        lines.pop();
    }
    lines.join("\n")
}

/// Mirrors `generate_tutorial.py::render_dirty_set`.
fn render_dirty_set(raw: &str) -> String {
    let lines: Vec<&str> = raw.split('\n').collect();
    let mut cut = lines.len();
    for (idx, l) in lines.iter().enumerate() {
        if l.trim_start().starts_with("-- Would run:") {
            cut = idx;
            break;
        }
    }
    render_text(&lines[..cut].join("\n"))
}

/// Mirrors `generate_tutorial.py::render_sql`.
fn render_sql(raw: &str) -> String {
    strip_sql_comments(&canonicalize(raw))
}

/// Mirrors `generate_tutorial.py::render_cells`.
fn render_cells(raw_stdout: &str, argv: &[String], marker: &str) -> String {
    assert!(
        argv.iter().any(|a| a == "--json"),
        "cells render mode requires --json in argv: {marker}"
    );
    let data: serde_json::Value = serde_json::from_str(raw_stdout).unwrap_or_else(|e| {
        panic!(
            "smelt {} did not print valid JSON: {e}\n{raw_stdout}",
            argv.join(" ")
        )
    });
    let cells = data["cells"].as_array().unwrap_or_else(|| {
        panic!(
            "smelt {} JSON has no 'cells' array: {raw_stdout}",
            argv.join(" ")
        )
    });
    let sql = render_cells_sql(cells);
    strip_sql_comments(&canonicalize(&sql))
}

/// Mirrors `generate_tutorial.py::render_include`. `<path>` is relative to
/// `examples/web_analytics/`. The leading `---`/`---` frontmatter block (if
/// present) is kept byte-for-byte; only the body after it has full-line
/// `--` comments stripped.
fn render_include(web_analytics_dir: &Path, path_rel: &str) -> String {
    let file_path = web_analytics_dir.join(path_rel);
    let text = fs::read_to_string(&file_path)
        .unwrap_or_else(|e| panic!("read include source {}: {e}", file_path.display()));
    let lines: Vec<&str> = text.split('\n').collect();

    let mut frontmatter: Vec<&str> = Vec::new();
    let mut body_start = 0usize;
    if !lines.is_empty() && lines[0].trim() == "---" {
        for idx in 1..lines.len() {
            if lines[idx].trim() == "---" {
                frontmatter = lines[..=idx].to_vec();
                body_start = idx + 1;
                break;
            }
        }
    }

    let body_lines = &lines[body_start..];
    let kept: Vec<&str> = body_lines
        .iter()
        .copied()
        .filter(|l| !l.trim_start().starts_with("--"))
        .collect();
    let body = collapse_and_trim(&kept);

    if !frontmatter.is_empty() {
        if !body.is_empty() {
            format!("{}\n{}", frontmatter.join("\n"), body)
        } else {
            frontmatter.join("\n")
        }
    } else {
        body
    }
}

// ---------------------------------------------------------------------------
// smelt invocation against a fresh temp workspace copy. Mirrors
// `generate_tutorial.py::_copy_workspace` / `WorkspaceCache` / `run_smelt`.
// ---------------------------------------------------------------------------

fn copy_dir_filtered(src: &Path, dest: &Path) {
    fs::create_dir_all(dest).unwrap_or_else(|e| panic!("mkdir {}: {e}", dest.display()));
    for entry in fs::read_dir(src).unwrap_or_else(|e| panic!("read_dir {}: {e}", src.display())) {
        let entry = entry.expect("dir entry");
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if EXCLUDE_NAMES.contains(&name_str.as_ref()) || name_str.ends_with(".duckdb") {
            continue;
        }
        let file_type = entry.file_type().expect("file type");
        let src_path = entry.path();
        let dest_path = dest.join(&name);
        if file_type.is_dir() {
            copy_dir_filtered(&src_path, &dest_path);
        } else if file_type.is_file() {
            fs::copy(&src_path, &dest_path).unwrap_or_else(|e| {
                panic!(
                    "copy {} -> {}: {e}",
                    src_path.display(),
                    dest_path.display()
                )
            });
        }
    }
}

/// Materializes (and reuses) one temp copy per (cwd, fixture-schemas) pair
/// within a single test run. Mirrors `generate_tutorial.py::WorkspaceCache`.
struct WorkspaceCache {
    tmp_root: PathBuf,
    web_analytics_dir: PathBuf,
    cache: HashMap<(String, bool), PathBuf>,
    counter: usize,
}

impl WorkspaceCache {
    fn new(tmp_root: PathBuf, web_analytics_dir: PathBuf) -> Self {
        Self {
            tmp_root,
            web_analytics_dir,
            cache: HashMap::new(),
            counter: 0,
        }
    }

    fn get(&mut self, cwd_rel: &str, fixture_schemas: bool) -> PathBuf {
        let key = (cwd_rel.to_string(), fixture_schemas);
        if let Some(p) = self.cache.get(&key) {
            return p.clone();
        }
        let src = if cwd_rel.is_empty() {
            self.web_analytics_dir.clone()
        } else {
            self.web_analytics_dir.join(cwd_rel)
        };
        self.counter += 1;
        let dest = self.tmp_root.join(format!("ws_{}", self.counter));
        copy_dir_filtered(&src, &dest);
        if fixture_schemas {
            // Fixtures land under the default `dev` target, matching the
            // `--target` these test invocations never pass
            // (`docs/specs/run_state.md` §"`.smelt/` directory layout").
            let schemas_dir = dest
                .join(".smelt")
                .join("targets")
                .join("dev")
                .join("schemas");
            fs::create_dir_all(&schemas_dir).expect("mkdir .smelt/targets/dev/schemas");
            let fixture_src = src.join("deployed_schema_fixture");
            if fixture_src.is_dir() {
                let mut entries: Vec<PathBuf> = fs::read_dir(&fixture_src)
                    .expect("read deployed_schema_fixture")
                    .map(|e| e.expect("dir entry").path())
                    .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
                    .collect();
                entries.sort();
                for path in entries {
                    let file_name = path.file_name().expect("file name");
                    fs::copy(&path, schemas_dir.join(file_name)).expect("copy fixture schema");
                }
            }
        }
        self.cache.insert(key, dest.clone());
        dest
    }
}

/// Runs the compiled `smelt` binary against a fresh temp copy of the
/// resolved workspace and returns its captured output per the exit-code
/// rule. Mirrors `generate_tutorial.py::run_smelt`.
fn run_smelt(
    argv: &[String],
    cwd_rel: &str,
    expect_exit: i32,
    fixture_schemas: bool,
    workspaces: &mut WorkspaceCache,
) -> String {
    let is_backbuild = argv.first().map(String::as_str) == Some("backbuild");
    let workspace = workspaces.get(cwd_rel, fixture_schemas);

    let mut full_args = argv.to_vec();
    if is_backbuild {
        let target_dir = workspace.join("target");
        fs::create_dir_all(&target_dir).expect("mkdir target");
        full_args.push("--database".to_string());
        full_args.push(target_dir.join("db.duckdb").to_string_lossy().into_owned());
    }

    let output = Command::new(env!("CARGO_BIN_EXE_smelt"))
        .args(&full_args)
        .current_dir(&workspace)
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "spawn smelt {} (cwd={}): {e}",
                full_args.join(" "),
                workspace.display()
            )
        });
    let code = output.status.code().unwrap_or(-1);
    assert_eq!(
        code,
        expect_exit,
        "smelt {} (cwd={}) exited {code}, expected {expect_exit}\nstdout:\n{}\nstderr:\n{}",
        full_args.join(" "),
        workspace.display(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    if expect_exit != 0 {
        format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
    } else {
        String::from_utf8_lossy(&output.stdout).into_owned()
    }
}

// ---------------------------------------------------------------------------
// `smelt-generate` directive parsing + dispatch. Mirrors
// `generate_tutorial.py::parse_generate_directive` / `render_generate`.
// ---------------------------------------------------------------------------

fn parse_generate_directive(rest: &str) -> (HashMap<String, Option<String>>, Vec<String>) {
    let tokens: Vec<&str> = rest.split_whitespace().collect();
    let mut opts: HashMap<String, Option<String>> = HashMap::new();
    let mut idx = 0;
    while idx < tokens.len() && tokens[idx].starts_with('@') {
        let tok = &tokens[idx][1..];
        if let Some(eq) = tok.find('=') {
            opts.insert(tok[..eq].to_string(), Some(tok[eq + 1..].to_string()));
        } else {
            opts.insert(tok.to_string(), None);
        }
        idx += 1;
    }
    let argv: Vec<String> = tokens[idx..].iter().map(|s| s.to_string()).collect();
    (opts, argv)
}

fn default_render_mode(subcommand: &str) -> Option<&'static str> {
    match subcommand {
        "explain" => Some("cells"),
        "backbuild" => Some("sql"),
        "run" => Some("text"),
        "diff" => Some("text"),
        _ => None,
    }
}

/// Re-derives a `smelt-generate` block's expected content by spawning the
/// real `smelt` binary. Returns `(content, mode)`; `mode` feeds the "at
/// least one of each kind" sanity assertions.
fn fresh_generate_block(rest: &str, workspaces: &mut WorkspaceCache) -> (String, String) {
    let (opts, argv) = parse_generate_directive(rest);
    assert!(
        !argv.is_empty(),
        "smelt-generate directive has no argv: {rest}"
    );
    let subcommand = argv[0].as_str();
    let is_backbuild = subcommand == "backbuild";

    let cwd_rel = opts.get("cwd").and_then(|v| v.clone()).unwrap_or_default();
    let expect_exit: i32 = opts
        .get("expect-exit")
        .and_then(|v| v.clone())
        .map(|v| {
            v.parse()
                .unwrap_or_else(|_| panic!("bad @expect-exit value in: {rest}"))
        })
        .unwrap_or(0);
    let fixture_schemas = opts.contains_key("fixture-schemas");

    let mode = opts
        .get("render")
        .and_then(|v| v.clone())
        .or_else(|| default_render_mode(subcommand).map(str::to_string))
        .unwrap_or_else(|| {
            panic!(
                "cannot infer a default render mode for argv[0]={subcommand:?}; \
                 specify @render=... in: {rest}"
            )
        });

    let raw = run_smelt(&argv, &cwd_rel, expect_exit, fixture_schemas, workspaces);

    let content = match mode.as_str() {
        "cells" => render_cells(&raw, &argv, rest),
        "sql" => render_sql(&raw),
        "skeleton" => {
            let base = if is_backbuild {
                render_sql(&raw)
            } else {
                render_cells(&raw, &argv, rest)
            };
            skeleton(&base)
        }
        "text" => render_text(&raw),
        "dirty-set" => render_dirty_set(&raw),
        other => panic!("unknown render mode {other:?} in: {rest}"),
    };
    (content, mode)
}

// ---------------------------------------------------------------------------
// Committed-page parsing: locate every directive + its following (possibly
// indented) fenced block, dedenting the fence content by the directive's own
// indentation before comparison.
// ---------------------------------------------------------------------------

struct FoundBlock {
    is_include: bool,
    /// For an include block: the source path. For a generate block: the
    /// directive's argument string (options + argv).
    payload: String,
    /// The fenced block's content, dedented to zero indentation.
    committed: String,
}

fn parse_page(page: &str, page_display: &dyn std::fmt::Display) -> Vec<FoundBlock> {
    let lines: Vec<&str> = page.lines().collect();
    let mut out = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim_start();
        let indent_len = line.len() - trimmed.len();
        let indent = &line[..indent_len];

        let (is_include, payload) = if let Some(rest) = trimmed
            .strip_prefix("<!-- smelt-include: ")
            .and_then(|s| s.strip_suffix(" -->"))
        {
            (true, rest.to_string())
        } else if let Some(rest) = trimmed
            .strip_prefix("<!-- smelt-generate: ")
            .and_then(|s| s.strip_suffix(" -->"))
        {
            (false, rest.to_string())
        } else {
            i += 1;
            continue;
        };

        let fence_open_idx = i + 1;
        assert!(
            fence_open_idx < lines.len(),
            "directive at line {} of {page_display} has no following fenced code block: {line}",
            i + 1
        );
        let fence_open_line = lines[fence_open_idx];
        let fence_prefix = format!("{indent}```");
        assert!(
            fence_open_line.starts_with(&fence_prefix),
            "directive at line {} of {page_display} is not immediately followed by a fence \
             indented `{indent:?}`; got: {fence_open_line:?}",
            i + 1
        );

        let close_line = fence_prefix.clone();
        let mut j = fence_open_idx + 1;
        while j < lines.len() && lines[j] != close_line {
            j += 1;
        }
        assert!(
            j < lines.len(),
            "fenced block opened at line {} of {page_display} (directive {payload:?}) is never closed",
            fence_open_idx + 1
        );

        let mut content_lines: Vec<&str> = Vec::new();
        for &l in &lines[fence_open_idx + 1..j] {
            let dedented = if indent.is_empty() {
                l
            } else if let Some(stripped) = l.strip_prefix(indent) {
                stripped
            } else if l.is_empty() {
                ""
            } else {
                panic!(
                    "content line inside the block starting at line {} of {page_display} \
                     doesn't carry the directive's indent {indent:?}: {l:?}",
                    fence_open_idx + 1
                );
            };
            content_lines.push(dedented);
        }
        let committed = content_lines.join("\n");

        out.push(FoundBlock {
            is_include,
            payload,
            committed,
        });
        i = j + 1;
    }
    out
}

// ---------------------------------------------------------------------------
// Test entry point
// ---------------------------------------------------------------------------

fn web_analytics_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples/web_analytics")
        .canonicalize()
        .expect("examples/web_analytics exists")
}

fn tutorial_pages_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs-site/docs/examples/web-analytics")
}

#[test]
fn web_analytics_tutorial_pages_are_fresh() {
    let pages_dir = tutorial_pages_dir();
    let mut page_paths: Vec<PathBuf> = fs::read_dir(&pages_dir)
        .unwrap_or_else(|e| {
            panic!(
                "failed to read {}: {e} — run `python3 examples/web_analytics/generate_tutorial.py` \
                 to generate the web-analytics tutorial pages",
                pages_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("md"))
        .collect();
    page_paths.sort();

    assert!(
        page_paths.len() >= 2,
        "expected at least 2 web-analytics tutorial pages under {}, found {}",
        pages_dir.display(),
        page_paths.len()
    );

    let web_analytics_dir = web_analytics_dir();
    let tmp = tempfile::TempDir::new().expect("create tempdir for workspace copies");
    let mut workspaces = WorkspaceCache::new(tmp.path().to_path_buf(), web_analytics_dir.clone());

    let mut found_include = false;
    let mut found_cells = false;
    let mut found_skeleton = false;
    let mut found_text = false;
    let mut found_sql = false;
    let mut found_dirty_set = false;

    for page_path in &page_paths {
        let page = fs::read_to_string(page_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", page_path.display()));
        let display = page_path.display();
        let blocks = parse_page(&page, &display);

        for block in blocks {
            if block.is_include {
                found_include = true;
                let fresh = render_include(&web_analytics_dir, &block.payload);
                assert_eq!(
                    fresh, block.committed,
                    "committed smelt-include block for `{}` in {} has drifted from a fresh \
                     re-derivation — run `python3 examples/web_analytics/generate_tutorial.py` \
                     to regenerate it",
                    block.payload, display
                );
            } else {
                let (fresh, mode) = fresh_generate_block(&block.payload, &mut workspaces);
                match mode.as_str() {
                    "cells" => found_cells = true,
                    "skeleton" => found_skeleton = true,
                    "text" => found_text = true,
                    "sql" => found_sql = true,
                    "dirty-set" => found_dirty_set = true,
                    _ => {}
                }
                assert_eq!(
                    fresh, block.committed,
                    "committed smelt-generate block for `smelt {}` in {} has drifted from a \
                     fresh re-derivation — run \
                     `python3 examples/web_analytics/generate_tutorial.py` to regenerate it",
                    block.payload, display
                );
            }
        }
    }

    assert!(
        found_include,
        "expected at least one smelt-include block across {}",
        pages_dir.display()
    );
    assert!(
        found_cells,
        "expected at least one 'cells'-mode smelt-generate block across {}",
        pages_dir.display()
    );
    assert!(
        found_skeleton,
        "expected at least one 'skeleton'-mode smelt-generate block across {}",
        pages_dir.display()
    );
    assert!(
        found_text,
        "expected at least one 'text'-mode smelt-generate block across {}",
        pages_dir.display()
    );
    assert!(
        found_sql,
        "expected at least one 'sql'-mode smelt-generate block across {}",
        pages_dir.display()
    );
    assert!(
        found_dirty_set,
        "expected at least one 'dirty-set'-mode smelt-generate block across {}",
        pages_dir.display()
    );
}
