#![cfg(feature = "duckdb")]
//! Phase 1.3 snapshot test — verifies that refactoring `events_parsed.sql`
//! to use `smelt.functions.parse_event_payload(payload).*` produces byte-equal
//! rows to the original inlined `json_extract_string(...)` calls.
//!
//! Rather than building the full `examples/web_analytics/` workspace (which
//! requires Parquet data files generated by smelt-datagen), this test stages
//! a minimal self-contained workspace with:
//!   - a CSV seed that stands in for `bronze.raw_events` (same column schema),
//!   - the `parse_event_payload` function declaration, and
//!   - two model variants of `events_parsed.sql`.
//!
//! The test builds both variants against the same CSV seed and asserts the
//! resulting rows are byte-equal.  Ordering is pinned by `ORDER BY event_id`
//! so the comparison is deterministic.

use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::TempDir;

// ─── Helpers (duplicated from functions_e2e.rs to keep tests self-contained) ──

fn smelt_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_smelt"))
}

fn write_workspace(tmp: &Path, files: &[(&str, &str)]) {
    for (rel, contents) in files {
        let path = tmp.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create parent dir");
        }
        std::fs::write(&path, contents).expect("write workspace file");
    }
}

fn run_smelt_build(project_dir: &Path, target: &str) {
    let output = Command::new(smelt_bin())
        .args([
            "build",
            "--project-dir",
            project_dir.to_str().unwrap(),
            "--target",
            target,
        ])
        .env("RUST_LOG", "warn")
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn `smelt build`: {e}"));
    assert!(
        output.status.success(),
        "smelt build (target={target}) failed (exit {:?})\nstdout:\n{}\nstderr:\n{}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

// ─── Shared workspace files ───────────────────────────────────────────────────

/// A small deterministic CSV seed that mirrors the `bronze.raw_events` schema
/// used by the real web_analytics workspace.  Five rows with known payloads so
/// the output is predictable.
const RAW_EVENTS_CSV: &str = "\
event_id,device_id,user_id,seconds_in_day,payload,event_date\n\
1,101,201,3600,\"{\"\"event_name\"\":\"\"page_view\"\",\"\"platform\"\":\"\"web\"\",\"\"url\"\":\"\"https://example.com/home\"\"}\",2026-03-19\n\
2,102,202,7200,\"{\"\"event_name\"\":\"\"click\"\",\"\"platform\"\":\"\"ios\"\",\"\"url\"\":\"\"https://example.com/product\"\"}\",2026-03-19\n\
3,103,203,10800,\"{\"\"event_name\"\":\"\"purchase\"\",\"\"platform\"\":\"\"android\"\",\"\"url\"\":\"\"https://example.com/checkout\"\"}\",2026-03-20\n\
4,104,204,14400,\"{\"\"event_name\"\":\"\"scroll\"\",\"\"platform\"\":\"\"web\"\",\"\"url\"\":\"\"https://example.com/product\"\"}\",2026-03-20\n\
5,105,205,18000,\"{\"\"event_name\"\":\"\"error\"\",\"\"platform\"\":\"\"ios\"\",\"\"url\"\":\"\"https://example.com/account\"\"}\",2026-03-21\n\
";

/// `parse_event_payload` function declaration (identical to the one in
/// `examples/web_analytics/functions/parse_event_payload.sql`).
const PARSE_EVENT_PAYLOAD_FN: &str = "\
---
backends: [duckdb]
---
smelt.define parse_event_payload(
    payload_json: Expr<Text>
) -> Expr<Struct<{event_name: Text, platform: Text, url: Text}>> AS (
    {
        json_extract_string(payload_json, '$.event_name') AS event_name,
        json_extract_string(payload_json, '$.platform') AS platform,
        json_extract_string(payload_json, '$.url') AS url
    }
)
";

/// Original `events_parsed.sql` — inlines the three `json_extract_string`
/// calls directly (no function call).
const EVENTS_PARSED_ORIGINAL: &str = "\
---
materialization: table
---
SELECT
    event_id,
    device_id,
    user_id,
    CAST(event_date AS DATE) + to_seconds(seconds_in_day) AS event_ts,
    CAST(event_date AS DATE) AS event_date,
    json_extract_string(payload, '$.event_name') AS event_name,
    json_extract_string(payload, '$.platform') AS platform,
    json_extract_string(payload, '$.url') AS url
FROM smelt.raw_events
ORDER BY event_id
";

/// Refactored `events_parsed.sql` — calls `smelt.functions.parse_event_payload`
/// with `.*` projection in place of the three inlined calls.
const EVENTS_PARSED_REFACTORED: &str = "\
---
materialization: table
---
SELECT
    event_id,
    device_id,
    user_id,
    CAST(event_date AS DATE) + to_seconds(seconds_in_day) AS event_ts,
    CAST(event_date AS DATE) AS event_date,
    smelt.functions.parse_event_payload(payload).*
FROM smelt.raw_events
ORDER BY event_id
";

fn smelt_yml_for(name: &str, db_path: &Path) -> String {
    format!(
        "name: {name}
version: 1
paths:
  - models
  - seeds
targets:
  dev:
    type: duckdb
    database: {db}
    schema: main
default_materialization: view
",
        db = db_path.display()
    )
}

// ─── Row type for the events_parsed output ────────────────────────────────────

#[derive(Debug, PartialEq)]
struct EventsParsedRow {
    event_id: i64,
    device_id: i64,
    user_id: Option<i64>,
    event_name: String,
    platform: String,
    url: String,
}

fn query_events_parsed(db_path: &Path) -> Vec<EventsParsedRow> {
    let conn = duckdb::Connection::open(db_path).expect("open duckdb");
    let mut stmt = conn
        .prepare(
            "SELECT event_id, device_id, user_id, event_name, platform, url \
             FROM main.events_parsed ORDER BY event_id",
        )
        .expect("prepare events_parsed query");
    stmt.query_map([], |row| {
        Ok(EventsParsedRow {
            event_id: row.get::<_, i64>(0)?,
            device_id: row.get::<_, i64>(1)?,
            user_id: row.get::<_, Option<i64>>(2)?,
            event_name: row.get::<_, String>(3)?,
            platform: row.get::<_, String>(4)?,
            url: row.get::<_, String>(5)?,
        })
    })
    .expect("query events_parsed rows")
    .collect::<Result<Vec<_>, _>>()
    .expect("collect rows")
}

// ─── Snapshot test ────────────────────────────────────────────────────────────

/// Build the *original* `events_parsed.sql` (three inlined `json_extract_string`
/// calls) and the *refactored* variant (`smelt.functions.parse_event_payload(payload).*`)
/// against the same deterministic CSV seed, then assert the resulting row sets
/// are identical.
///
/// This is the TDD gate for Phase 1.3 of
/// `docs/plans/20260519-functions-meta-1-call-expansion.md`.  The test is RED
/// until `examples/web_analytics/models/silver/events_parsed.sql` is rewritten
/// to use the function call.
#[test]
fn events_parsed_rowset_equivalent_after_refactor() {
    // ── Build original variant ──────────────────────────────────────────────
    let tmp_orig = TempDir::new().expect("tempdir");
    let db_orig = tmp_orig.path().join("orig.duckdb");
    let yml_orig = smelt_yml_for("snapshot_original", &db_orig);
    write_workspace(
        tmp_orig.path(),
        &[
            ("smelt.yml", yml_orig.as_str()),
            ("seeds/raw_events.csv", RAW_EVENTS_CSV),
            ("functions/parse_event_payload.sql", PARSE_EVENT_PAYLOAD_FN),
            ("models/events_parsed.sql", EVENTS_PARSED_ORIGINAL),
        ],
    );
    run_smelt_build(tmp_orig.path(), "dev");
    let rows_original = query_events_parsed(&db_orig);

    // ── Build refactored variant ────────────────────────────────────────────
    let tmp_ref = TempDir::new().expect("tempdir");
    let db_ref = tmp_ref.path().join("ref.duckdb");
    let yml_ref = smelt_yml_for("snapshot_refactored", &db_ref);
    write_workspace(
        tmp_ref.path(),
        &[
            ("smelt.yml", yml_ref.as_str()),
            ("seeds/raw_events.csv", RAW_EVENTS_CSV),
            ("functions/parse_event_payload.sql", PARSE_EVENT_PAYLOAD_FN),
            ("models/events_parsed.sql", EVENTS_PARSED_REFACTORED),
        ],
    );
    run_smelt_build(tmp_ref.path(), "dev");
    let rows_refactored = query_events_parsed(&db_ref);

    // ── Assert byte-equal row sets ─────────────────────────────────────────
    assert_eq!(
        rows_original.len(),
        5,
        "original: expected 5 rows, got: {rows_original:?}"
    );
    assert_eq!(
        rows_refactored.len(),
        5,
        "refactored: expected 5 rows, got: {rows_refactored:?}"
    );
    assert_eq!(
        rows_original, rows_refactored,
        "Row sets differ between original (inlined json_extract_string) \
         and refactored (parse_event_payload.* projection).\n\
         original:   {rows_original:?}\n\
         refactored: {rows_refactored:?}"
    );
}
