#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# ── Wizard-specific configuration ─────────────────────────────────────────
#
# Everything this wizard creates is deliberately kept OUT of the ambient
# credential locations. `~/.config/gcloud` (the path every Google client
# library probes by default) is never written to, so a process that has not
# been told about this setup finds no credentials at all.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
BQ_CONFIG_DIR="${SMELT_BQ_CONFIG_DIR:-$HOME/.config/gcloud-smelt-bq}"
ENV_FILE="$BQ_CONFIG_DIR/config.env"     # wizard library writes captured values here
KEY_ENC="$BQ_CONFIG_DIR/sa-key.json.gpg" # service-account key, encrypted at rest
TOKEN_FILE="$BQ_CONFIG_DIR/token"        # short-lived access token (1h)

mkdir -p "$BQ_CONFIG_DIR"
chmod 700 "$BQ_CONFIG_DIR"

# gc — run gcloud against the ISOLATED config dir, never the user's default.
gc() { CLOUDSDK_CONFIG="$BQ_CONFIG_DIR" gcloud "$@"; }
# bqc — same, for the `bq` CLI that ships with the SDK.
bqc() { CLOUDSDK_CONFIG="$BQ_CONFIG_DIR" bq "$@"; }

banner "smelt · BigQuery backend provisioning"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Google Cloud CLI"
say "smelt's BigQuery tests drive the gcloud + bq CLIs. Let's make sure they exist."
if command -v gcloud >/dev/null 2>&1 && command -v bq >/dev/null 2>&1; then
  note "found $(gcloud version 2>/dev/null | head -n1)"
else
  warn "gcloud (and its bundled bq) are not installed."
  say "Install it, then come back to this terminal and press Enter."
  open_url "https://cloud.google.com/sdk/docs/install#linux"
  step "Follow the install for your platform, then run: gcloud version"
  pause "Press Enter once 'gcloud version' works in a NEW terminal…"
  if ! command -v gcloud >/dev/null 2>&1; then
    warn "still can't find gcloud on PATH — open a new shell and re-run this wizard."
    exit 1
  fi
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Sign in (isolated credential store)"
say "We sign in to a PRIVATE gcloud config directory, not your default one:"
note "  $BQ_CONFIG_DIR"
say "Nothing is written to ~/.config/gcloud, so no tool — including an AI"
say "coding session — picks these credentials up ambiently."
if gc auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  note "already signed in as $(gc auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -n1)"
else
  step "A browser window will open — sign in with your Google Cloud account."
  gc auth login || { warn "sign-in failed"; exit 1; }
fi
BQ_ACCOUNT="$(gc auth list --filter=status:ACTIVE --format='value(account)' | head -n1)"
note "active account: $BQ_ACCOUNT"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Dedicated project"
say "smelt's tests get their OWN project. That is the blast-radius control:"
say "if this setup is ever compromised, the damage is bounded to this project."
say ""
say "Existing projects on this account:"
gc projects list --format='table(projectId,name)' 2>/dev/null | head -n 15 || true
say ""
say "Enter a project ID to use. It must be globally unique across all of GCP."
note "suggestion: smelt-bq-test-$(od -An -N2 -tu2 /dev/urandom | tr -d ' ')"
ask SMELT_BQ_PROJECT "Project ID:"
if [[ -z "${SMELT_BQ_PROJECT:-}" ]]; then warn "a project ID is required"; exit 1; fi

if gc projects describe "$SMELT_BQ_PROJECT" >/dev/null 2>&1; then
  note "project $SMELT_BQ_PROJECT already exists — using it"
else
  if confirm "Create new project '$SMELT_BQ_PROJECT'?"; then
    gc projects create "$SMELT_BQ_PROJECT" || { warn "project creation failed"; exit 1; }
  else
    warn "cannot continue without a project"; exit 1
  fi
fi
gc config set project "$SMELT_BQ_PROJECT" >/dev/null 2>&1
write_env SMELT_BQ_PROJECT "$SMELT_BQ_PROJECT"

say ""
say "BigQuery needs billing enabled (the free tier still requires a linked account)."
if gc billing projects describe "$SMELT_BQ_PROJECT" --format='value(billingEnabled)' 2>/dev/null | grep -qi true; then
  note "billing already linked"
else
  say "Available billing accounts:"
  gc billing accounts list --format='table(name,displayName,open)' 2>/dev/null || true
  ask SMELT_BQ_BILLING "Billing account ID (e.g. 0X0X0X-0X0X0X-0X0X0X):"
  if [[ -n "${SMELT_BQ_BILLING:-}" ]]; then
    gc billing projects link "$SMELT_BQ_PROJECT" --billing-account="$SMELT_BQ_BILLING" >/dev/null 2>&1 \
      || warn "couldn't link billing — do it in the console before running tests"
    write_env SMELT_BQ_BILLING "$SMELT_BQ_BILLING"
  else
    SKIPPED+=("link a billing account to $SMELT_BQ_PROJECT")
  fi
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Enable the BigQuery API"
say "Turning on the APIs this project needs. This can take a minute."
gc services enable bigquery.googleapis.com --project="$SMELT_BQ_PROJECT" 2>/dev/null \
  && note "bigquery.googleapis.com enabled" \
  || warn "couldn't enable bigquery.googleapis.com — check billing is linked"
gc services enable iam.googleapis.com --project="$SMELT_BQ_PROJECT" >/dev/null 2>&1 || true

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Test dataset (with self-expiring tables)"
say "Tests create tables constantly and don't always get to clean up — a panic"
say "or Ctrl-C leaves orphans behind. We set a DEFAULT TABLE EXPIRATION on the"
say "dataset so every table self-deletes after 24h. Cleanup becomes structural."
ask SMELT_BQ_DATASET "Dataset name [smelt_test]:"
SMELT_BQ_DATASET="${SMELT_BQ_DATASET:-smelt_test}"
ask SMELT_BQ_LOCATION "Dataset location [US]:"
SMELT_BQ_LOCATION="${SMELT_BQ_LOCATION:-US}"

if bqc --project_id="$SMELT_BQ_PROJECT" show --dataset "$SMELT_BQ_PROJECT:$SMELT_BQ_DATASET" >/dev/null 2>&1; then
  note "dataset already exists — leaving it as-is"
else
  bqc --project_id="$SMELT_BQ_PROJECT" mk \
      --dataset \
      --location="$SMELT_BQ_LOCATION" \
      --default_table_expiration=86400 \
      --description="smelt integration tests — tables expire after 24h" \
      "$SMELT_BQ_PROJECT:$SMELT_BQ_DATASET" >/dev/null 2>&1 \
    && note "created $SMELT_BQ_DATASET (tables expire after 24h)" \
    || warn "dataset creation failed — check the API is enabled"
fi
write_env SMELT_BQ_DATASET "$SMELT_BQ_DATASET"
write_env SMELT_BQ_LOCATION "$SMELT_BQ_LOCATION"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Least-privilege service account"
say "Tests authenticate as a service account, NOT as you."
say ""
say "This matters: your own credentials carry your full Google Cloud identity"
say "across every project you can reach. The service account below can only"
say "run BigQuery jobs in this one project and write to this one dataset."
SMELT_BQ_SA="smelt-bq-test@${SMELT_BQ_PROJECT}.iam.gserviceaccount.com"

if gc iam service-accounts describe "$SMELT_BQ_SA" --project="$SMELT_BQ_PROJECT" >/dev/null 2>&1; then
  note "service account already exists"
else
  gc iam service-accounts create smelt-bq-test \
      --project="$SMELT_BQ_PROJECT" \
      --display-name="smelt integration tests" >/dev/null 2>&1 \
    && note "created $SMELT_BQ_SA" \
    || { warn "service-account creation failed"; exit 1; }
fi

say ""
step "Granting roles/bigquery.jobUser at project scope (run queries, no data access)."
gc projects add-iam-policy-binding "$SMELT_BQ_PROJECT" \
    --member="serviceAccount:$SMELT_BQ_SA" \
    --role="roles/bigquery.jobUser" >/dev/null 2>&1 \
  && note "jobUser granted" || warn "couldn't grant jobUser"

step "Granting dataEditor on '$SMELT_BQ_DATASET' ONLY (not project-wide)."
_acl_tmp="$(mktemp)"; _acl_new="$(mktemp)"
if bqc --project_id="$SMELT_BQ_PROJECT" show --format=prettyjson \
      --dataset "$SMELT_BQ_PROJECT:$SMELT_BQ_DATASET" > "$_acl_tmp" 2>/dev/null; then
  jq --arg sa "$SMELT_BQ_SA" \
     '.access += [{"role":"WRITER","userByEmail":$sa}] | .access |= unique' \
     "$_acl_tmp" > "$_acl_new"
  bqc --project_id="$SMELT_BQ_PROJECT" update --source "$_acl_new" \
      "$SMELT_BQ_PROJECT:$SMELT_BQ_DATASET" >/dev/null 2>&1 \
    && note "dataset-scoped WRITER granted" \
    || warn "couldn't update dataset ACL — grant WRITER on $SMELT_BQ_DATASET by hand"
else
  warn "couldn't read dataset ACL — grant WRITER on $SMELT_BQ_DATASET by hand"
fi
rm -f "$_acl_tmp" "$_acl_new"
write_env SMELT_BQ_SA "$SMELT_BQ_SA"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Encrypt the key at rest"
say "Now the important part."
say ""
say "A service-account key is a long-lived credential. Left in plaintext, any"
say "process running as you — including an AI coding session — can read it and"
say "use it forever. So we encrypt it with a passphrase you type."
say ""
say "Effect: minting BigQuery access requires a HUMAN. An agent cannot decrypt"
say "this file without the passphrase, and the plaintext key never hits disk."
say ""
if [[ -f "$KEY_ENC" ]]; then
  note "encrypted key already present at $KEY_ENC"
  if ! confirm "Replace it with a freshly-minted key?"; then
    note "keeping existing key"
  else
    rm -f "$KEY_ENC"
  fi
fi

if [[ ! -f "$KEY_ENC" ]]; then
  _key_plain="$(mktemp)"
  gc iam service-accounts keys create "$_key_plain" \
      --iam-account="$SMELT_BQ_SA" \
      --project="$SMELT_BQ_PROJECT" >/dev/null 2>&1 \
    || { rm -f "$_key_plain"; warn "key creation failed"; exit 1; }

  say "Choose a passphrase. You'll type it each time you start a test session."
  if command -v gpg >/dev/null 2>&1; then
    gpg --batch --yes --symmetric --cipher-algo AES256 \
        --output "$KEY_ENC" "$_key_plain" \
      || { rm -f "$_key_plain"; warn "encryption failed"; exit 1; }
  else
    openssl enc -aes-256-cbc -pbkdf2 -salt -in "$_key_plain" -out "$KEY_ENC" \
      || { rm -f "$_key_plain"; warn "encryption failed"; exit 1; }
  fi
  # Shred the plaintext — never leave it recoverable.
  command -v shred >/dev/null 2>&1 && shred -u "$_key_plain" 2>/dev/null || rm -f "$_key_plain"
  chmod 600 "$KEY_ENC"
  note "encrypted key written to $KEY_ENC (plaintext shredded)"
fi

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Budget cap"
say "Test tables are kilobytes and BigQuery's free tier is 1 TiB/month, so the"
say "expected spend here is zero. A budget alert is cheap insurance against a"
say "runaway generative test looping over a large scan."
warn "A GCP budget ALERTS — it does not hard-stop spending."
if [[ -n "${SMELT_BQ_BILLING:-}" ]]; then
  gc services enable billingbudgets.googleapis.com --project="$SMELT_BQ_PROJECT" >/dev/null 2>&1 || true
  if gc billing budgets create \
       --billing-account="$SMELT_BQ_BILLING" \
       --display-name="smelt-bq-test cap" \
       --budget-amount=5USD \
       --filter-projects="projects/$SMELT_BQ_PROJECT" >/dev/null 2>&1; then
    note "US\$5/month budget alert created"
  else
    SKIPPED+=("create a budget alert on $SMELT_BQ_PROJECT (console → Billing → Budgets)")
    warn "couldn't create the budget automatically"
    open_url "https://console.cloud.google.com/billing/budgets"
    pause "Set a small budget in the console if you want one, then press Enter…"
  fi
else
  SKIPPED+=("create a budget alert on $SMELT_BQ_PROJECT")
fi

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Generate the auth + env scripts"
say "Two scripts get written into the repo:"
note "  scripts/bigquery-auth.sh — you run this; decrypts the key, mints a 1h token"
note "  scripts/bigquery-env.sh  — tests source this; exports project/dataset/token"

cat > "$REPO_ROOT/scripts/bigquery-auth.sh" <<AUTHEOF
#!/usr/bin/env bash
# bigquery-auth.sh — mint a SHORT-LIVED (1 hour) BigQuery access token.
#
# Run this yourself at the start of a BigQuery test session:
#
#     bash scripts/bigquery-auth.sh
#
# It prompts for the passphrase protecting the service-account key, mints an
# OAuth access token, and writes it to \$BQ_CONFIG_DIR/token with an expiry
# stamp. The plaintext key is never written to disk.
#
# Outside the one-hour window there is no usable credential on this machine,
# and minting a new one requires a human to type the passphrase.
set -euo pipefail

BQ_CONFIG_DIR="\${SMELT_BQ_CONFIG_DIR:-\$HOME/.config/gcloud-smelt-bq}"
KEY_ENC="\$BQ_CONFIG_DIR/sa-key.json.gpg"
TOKEN_FILE="\$BQ_CONFIG_DIR/token"

[[ -f "\$KEY_ENC" ]] || { echo "no encrypted key at \$KEY_ENC — run scripts/bigquery-setup.sh" >&2; exit 1; }

_plain="\$(mktemp)"
trap 'command -v shred >/dev/null 2>&1 && shred -u "\$_plain" 2>/dev/null || rm -f "\$_plain"' EXIT

if command -v gpg >/dev/null 2>&1; then
  gpg --quiet --decrypt --output "\$_plain" "\$KEY_ENC"
else
  openssl enc -d -aes-256-cbc -pbkdf2 -in "\$KEY_ENC" -out "\$_plain"
fi

CLOUDSDK_CONFIG="\$BQ_CONFIG_DIR" gcloud auth activate-service-account \\
  --key-file="\$_plain" --quiet >/dev/null 2>&1

TOKEN="\$(CLOUDSDK_CONFIG="\$BQ_CONFIG_DIR" gcloud auth print-access-token)"
EXPIRES=\$(( \$(date +%s) + 3500 ))

umask 077
printf '%s\\n%s\\n' "\$TOKEN" "\$EXPIRES" > "\$TOKEN_FILE"
chmod 600 "\$TOKEN_FILE"

echo "BigQuery token minted — valid until \$(date -d "@\$EXPIRES" '+%H:%M:%S')"
echo "Now run:  source scripts/bigquery-env.sh"
AUTHEOF
chmod +x "$REPO_ROOT/scripts/bigquery-auth.sh"
note "wrote scripts/bigquery-auth.sh"

cat > "$REPO_ROOT/scripts/bigquery-env.sh" <<'ENVEOF'
# bigquery-env.sh — source this (`source scripts/bigquery-env.sh`) to point
# smelt's BigQuery integration tests at your provisioned GCP project.
#
#   SMELT_BQ_PROJECT      — gate + target project for the BigQuery backend tests.
#                           When UNSET, all BigQuery-targeted tests skip (green).
#   SMELT_BQ_DATASET      — base dataset; per-run test datasets are suffixed.
#   SMELT_BQ_LOCATION     — dataset location (must match at query time).
#   SMELT_BQ_ACCESS_TOKEN — short-lived OAuth token from bigquery-auth.sh.
#
# The adapter authenticates with SMELT_BQ_ACCESS_TOKEN *explicitly* and never
# falls back to application-default credentials. That is deliberate: it makes
# ambient credentials unusable, so the only way to reach GCP is the token this
# script exports.
_bq_config_dir="${SMELT_BQ_CONFIG_DIR:-$HOME/.config/gcloud-smelt-bq}"
_bq_env_file="${_bq_config_dir}/config.env"

if [ -f "${_bq_env_file}" ]; then
  # shellcheck disable=SC1090
  . "${_bq_env_file}"
  export SMELT_BQ_PROJECT SMELT_BQ_DATASET SMELT_BQ_LOCATION
else
  echo "no config at ${_bq_env_file} — run: bash scripts/bigquery-setup.sh" >&2
fi

_bq_token_file="${_bq_config_dir}/token"
if [ -f "${_bq_token_file}" ]; then
  _bq_expires="$(sed -n '2p' "${_bq_token_file}")"
  if [ -n "${_bq_expires}" ] && [ "$(date +%s)" -lt "${_bq_expires}" ]; then
    SMELT_BQ_ACCESS_TOKEN="$(sed -n '1p' "${_bq_token_file}")"
    export SMELT_BQ_ACCESS_TOKEN
    echo "SMELT_BQ_ACCESS_TOKEN valid until $(date -d "@${_bq_expires}" '+%H:%M:%S')"
  else
    unset SMELT_BQ_ACCESS_TOKEN
    echo "BigQuery token expired — run: bash scripts/bigquery-auth.sh" >&2
  fi
else
  echo "no BigQuery token — run: bash scripts/bigquery-auth.sh" >&2
fi

echo "SMELT_BQ_PROJECT=${SMELT_BQ_PROJECT:-<unset>}"
echo "SMELT_BQ_DATASET=${SMELT_BQ_DATASET:-<unset>}"
ENVEOF
note "wrote scripts/bigquery-env.sh"

say ""
say "Let's prove the whole chain works end to end."
if confirm "Mint a token now and run a probe query?"; then
  bash "$REPO_ROOT/scripts/bigquery-auth.sh" || warn "token minting failed"
  if [[ -f "$TOKEN_FILE" ]]; then
    _tok="$(sed -n '1p' "$TOKEN_FILE")"
    if curl -sS -H "Authorization: Bearer $_tok" \
         -H "Content-Type: application/json" \
         -d '{"query":"SELECT 1 AS ok","useLegacySql":false}' \
         "https://bigquery.googleapis.com/bigquery/v2/projects/$SMELT_BQ_PROJECT/queries" \
         | jq -e '.rows[0].f[0].v == "1"' >/dev/null 2>&1; then
      note "probe query succeeded — the service account can run BigQuery jobs"
    else
      warn "probe query failed — IAM propagation can take a minute; retry shortly"
    fi
  fi
else
  SKIPPED+=("verify with: bash scripts/bigquery-auth.sh && source scripts/bigquery-env.sh")
fi

finish

printf '  %sTo start a BigQuery test session:%s\n' "$BOLD" "$RESET"
note "  bash scripts/bigquery-auth.sh     # type passphrase — mints a 1h token"
note "  source scripts/bigquery-env.sh    # exports project/dataset/token"
note "  cargo test -p smelt-cli --features smelt-cli/bigquery --test bigquery_smoke"
printf '\n'
warn "Never copy the encrypted key or the token file into the repo."
printf '\n'
