#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# shellcheck disable=SC2034  # RED belongs to the shared palette, unused here
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — phase 7 tasks 1–5 of docs/outcomes/20260906-bigquery-dogfood-spine.
#
# Reuses the EXISTING project smelt-bq-test-20260816 (D0, human decision of
# 2026-09-09) and adds a new no-expiry dataset beside the test one. It does not
# create a project and does not touch smelt_test or the smelt-bq-test@ service
# account.
#
# This runs in your ORDINARY gcloud config, deliberately: the dogfood path uses
# ADC in ~/.config/gcloud, while the test project's credentials stay in the
# isolated CLOUDSDK_CONFIG that scripts/bigquery-auth.sh uses. If you have
# CLOUDSDK_CONFIG exported, stage 1 unsets it for this run.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

PROJECT="smelt-bq-test-20260816"
DATASET="smelt_dogfood"
LOCATION="US"
SA_NAME="smelt-dogfood"
SA="${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
BUDGET_USD=25

# The dogfood path is ADC in the default config. An inherited CLOUDSDK_CONFIG
# would silently provision into the test project's isolated config instead.
unset CLOUDSDK_CONFIG
[[ -d "$HOME/google-cloud-sdk/bin" ]] && export PATH="$HOME/google-cloud-sdk/bin:$PATH"
GCLOUD="$(command -v gcloud || echo "$HOME/google-cloud-sdk/bin/gcloud")"
API="https://bigquery.googleapis.com/bigquery/v2"

# Dataset work goes through REST rather than `bq`: `bq` imports pyOpenSSL on the
# SDK's bundled Python and dies on some installs, and every other script in this
# repo already speaks REST over curl. One way of talking to BigQuery, not two.
bq_status() {
  curl -sS -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $("$GCLOUD" auth print-access-token)" "${API}/$1"
}
bq_call() {
  local method="$1" path="$2" body="${3:-}" resp msg tok
  tok="$("$GCLOUD" auth print-access-token)"
  if [[ -n "$body" ]]; then
    resp=$(curl -sS -X "$method" -H "Authorization: Bearer ${tok}" \
      -H "Content-Type: application/json" -d "$body" "${API}/${path}")
  else
    resp=$(curl -sS -X "$method" -H "Authorization: Bearer ${tok}" "${API}/${path}")
  fi
  msg=$(jq -r '.error.message // ""' <<<"$resp")
  if [[ -n "$msg" ]]; then
    echo "API ${method} ${path} failed: ${msg}" >&2
    return 1
  fi
  printf '%s' "$resp"
}

banner "smelt BigQuery dogfood — dataset, budget, and a scoped credential"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Sign in as yourself"
say "Provisioning enables APIs and edits IAM. Neither the dogfood service"
say "account nor smelt-bq-test@ can do that — it needs your human identity."
for tool in curl jq; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool is required but missing."; exit 1; }
done
[[ -x "$GCLOUD" ]] || { warn "gcloud not found. Install the SDK first."; exit 1; }

ADMIN="$("$GCLOUD" auth list --format='value(account)' 2>/dev/null \
        | grep -v 'gserviceaccount\.com' | head -n1 || true)"
if [[ -z "$ADMIN" ]]; then
  step "A browser will open for Google sign-in. Use the account that owns $PROJECT."
  pause "Press Enter to sign in"
  "$GCLOUD" auth login
  ADMIN="$("$GCLOUD" auth list --format='value(account)' 2>/dev/null \
          | grep -v 'gserviceaccount\.com' | head -n1 || true)"
fi
[[ -n "$ADMIN" ]] || { warn "still no human account signed in — cannot continue."; exit 1; }
export CLOUDSDK_CORE_ACCOUNT="$ADMIN"
say "Admin identity: ${BOLD}${ADMIN}${RESET}"
say "Project:        ${BOLD}${PROJECT}${RESET}  (reused, not created)"
say "New dataset:    ${BOLD}${DATASET}${RESET} in ${LOCATION}, no table expiry"
note "smelt_test and its 24h expiry are left exactly as they are."
confirm "Proceed against $PROJECT as $ADMIN?" || { warn "aborted."; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Enable the APIs"
say "bigquery.googleapis.com is already on (the test suites run against it);"
say "billingbudgets.googleapis.com is the one this phase actually needs."
"$GCLOUD" services enable bigquery.googleapis.com --project="$PROJECT"
"$GCLOUD" services enable billingbudgets.googleapis.com --project="$PROJECT"
say "both enabled"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the no-expiry dataset"
say "This is the whole reason a second dataset exists: smelt_test expires its"
say "tables after 24h, which would shred a pipeline meant to accumulate history."
if [[ "$(bq_status "projects/${PROJECT}/datasets/${DATASET}")" == "200" ]]; then
  say "${DATASET} already exists — leaving it alone."
else
  body=$(jq -n --arg p "$PROJECT" --arg d "$DATASET" --arg loc "$LOCATION" \
    '{datasetReference: {projectId: $p, datasetId: $d}, location: $loc,
      description: "smelt dogfood pipeline — tables must NOT expire"}')
  bq_call POST "projects/${PROJECT}/datasets" "$body" >/dev/null
  say "created ${DATASET}"
fi
say "Reading the expiry back from the API — a successful create is not evidence:"
exp=$(bq_call GET "projects/${PROJECT}/datasets/${DATASET}" \
      | jq -r '.defaultTableExpirationMs // "ABSENT"')
if [[ "$exp" == "ABSENT" ]]; then
  say "  defaultTableExpirationMs = ABSENT — correct."
else
  warn "defaultTableExpirationMs = $exp — WRONG. Tables will vanish."
  warn "Clear it in the console before running any pipeline against this dataset."
  SKIPPED+=("clear defaultTableExpirationMs on ${DATASET} (currently $exp)")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Raise the budget to US\$${BUDGET_USD}/month"
say "The existing cap is US\$5, sized for short test suites. The dogfood runs"
say "need more. This raises the cap for everything in the project — the"
say "accepted cost of reusing it rather than provisioning a second project."
BILLING="$("$GCLOUD" billing projects describe "$PROJECT" \
          --format='value(billingAccountName)' 2>/dev/null | sed 's#billingAccounts/##' || true)"
if [[ -z "$BILLING" ]]; then
  ask BILLING "Billing account ID (XXXXXX-XXXXXX-XXXXXX):"
fi
say "Billing account: $BILLING"
existing="$("$GCLOUD" billing budgets list --billing-account="$BILLING" \
           --filter="displayName~smelt" --format='value(name)' 2>/dev/null | head -n1 || true)"
if [[ -n "$existing" ]]; then
  say "Updating existing budget: ${existing##*/}"
  if "$GCLOUD" billing budgets update "$existing" \
       --billing-account="$BILLING" --budget-amount="${BUDGET_USD}USD" >/dev/null; then
    say "budget now US\$${BUDGET_USD}/month"
  else
    warn "update failed"
    SKIPPED+=("raise the budget to US\$${BUDGET_USD}")
  fi
else
  if "$GCLOUD" billing budgets create --billing-account="$BILLING" \
       --display-name="smelt-bq dogfood cap" --budget-amount="${BUDGET_USD}USD" \
       --filter-projects="projects/${PROJECT}" >/dev/null; then
    say "budget created at US\$${BUDGET_USD}/month"
  else
    warn "create failed — do it in the console"
    open_url "https://console.cloud.google.com/billing/budgets"
    SKIPPED+=("create a US\$${BUDGET_USD} budget for ${PROJECT}")
  fi
fi
note "A budget ALERTS. It does not hard-stop spend."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the dogfood service account and grant it"
say "A second, separate identity from smelt-bq-test@ — that one keeps its"
say "gpg-encrypted key and its isolated config, untouched."
if "$GCLOUD" iam service-accounts describe "$SA" --project="$PROJECT" >/dev/null 2>&1; then
  say "$SA already exists"
else
  "$GCLOUD" iam service-accounts create "$SA_NAME" \
     --project="$PROJECT" --display-name="smelt dogfood pipeline"
  say "created $SA"
fi

say "Granting roles/bigquery.jobUser at project scope (run jobs) ..."
note "Deliberately NOT bigquery.user: unlike the test suites, this pipeline"
note "writes to one long-lived dataset and never creates datasets of its own."
"$GCLOUD" projects add-iam-policy-binding "$PROJECT" \
   --member="serviceAccount:${SA}" --role="roles/bigquery.jobUser" \
   --condition=None >/dev/null
say "granted"

say "Granting WRITER on ${DATASET} only ..."
note "PATCH replaces the access array wholesale, so existing entries —"
note "including smelt-bq-test@'s — are read and carried forward."
acl=$(bq_call GET "projects/${PROJECT}/datasets/${DATASET}" \
      | jq --arg sa "$SA" '{access: ((.access // []) + [{"role":"WRITER","userByEmail":$sa}] | unique)}')
bq_call PATCH "projects/${PROJECT}/datasets/${DATASET}" "$acl" >/dev/null
say "granted"

say "Granting you roles/iam.serviceAccountTokenCreator on it ..."
note "Easy to miss. Without it the next stage fails with a confusing"
note "PERMISSION_DENIED that says nothing about impersonation."
"$GCLOUD" iam service-accounts add-iam-policy-binding "$SA" \
   --project="$PROJECT" --member="user:${ADMIN}" \
   --role="roles/iam.serviceAccountTokenCreator" >/dev/null
say "granted"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Log in as ADC, impersonating the dogfood account"
say "The effective identity becomes a service account holding roles on this"
say "project only — so the pipeline, and any session driving it, cannot reach"
say "your other GCP projects. No key material is minted or stored."
step "A browser opens. Sign in as $ADMIN — the impersonation is applied after."
pause "Press Enter to start the ADC login"
"$GCLOUD" auth application-default login \
   --impersonate-service-account="$SA"
"$GCLOUD" auth application-default set-quota-project "$PROJECT" >/dev/null 2>&1 || true
"$GCLOUD" config set project "$PROJECT" >/dev/null
say "ADC configured, default project set to $PROJECT"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Prove the reach is real, not nominal"
say "An impersonated login that silently fell back to your own identity would"
say "pass every other check. These are the ones that catch it."

say ""
say "1. bq is usable, or it isn't (either answer is fine — the repo speaks REST):"
if bq version >/dev/null 2>&1; then
  say "   $(bq version 2>&1 | head -n1)"
else
  note "   bq is broken here (the known pyOpenSSL import failure). Use REST."
fi

say ""
say "2. The dataset lists under the impersonated credential:"
bq_call GET "projects/${PROJECT}/datasets/${DATASET}" \
  | jq -r '"   \(.datasetReference.datasetId) in \(.location), expiry=\(.defaultTableExpirationMs // "ABSENT")"'

say ""
say "3. The ACL is what we think it is:"
bq_call GET "projects/${PROJECT}/datasets/${DATASET}" \
  | jq -r '.access[] | "   \(.role)\t\(.userByEmail // .specialGroup // .groupByEmail // "-")"'

say ""
say "4. A DIFFERENT project of yours is refused."
note "Reachability into smelt_test in THIS project is expected to SUCCEED —"
note "bigquery.jobUser is project-scoped. That is the accepted cost of reuse,"
note "not a scoping failure. What must fail is another project entirely."
ask OTHER_PROJECT "Another project ID of yours to test against (Enter to skip):"
if [[ -n "${OTHER_PROJECT:-}" ]]; then
  if [[ "$(bq_status "projects/${OTHER_PROJECT}/datasets")" == "200" ]]; then
    warn "   ${OTHER_PROJECT} was READABLE — impersonation is not scoping as intended."
    SKIPPED+=("investigate: ${OTHER_PROJECT} is reachable under the dogfood credential")
  else
    say "   refused, as it must be"
  fi
else
  SKIPPED+=("run the cross-project refusal check (stage 7, step 4)")
fi

finish
