#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# shellcheck disable=SC2034  # RED belongs to the shared palette, unused here
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — phase 4b of docs/outcomes/20260912-databricks-dogfood-spine.
#
# Creates the two dogfood schemas (smelt_dogfood, smelt_dogfood_oracle) in
# the `workspace` catalog of a Databricks Free Edition workspace, mints a
# scoped credential (kind decided empirically — Free Edition may or may not
# permit a service-principal OAuth M2M secret), grants that credential on
# the two schemas only, and hands off to scripts/dbx-verify.sh to prove
# reachability and out-of-scope-write refusal before recording the Free
# Edition quotas.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

CATALOG="workspace"
SCHEMA="smelt_dogfood"
ORACLE_SCHEMA="smelt_dogfood_oracle"
FACTS_SHEET="docs/outcomes/20260912-databricks-dogfood-spine/free-edition-facts.md"

banner "smelt Databricks dogfood — schemas, credential, and reachability"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the Free Edition workspace"
say "Free Edition is serverless-only and Unity-Catalog-only — no cluster to"
say "create, no warehouse path to configure."
step "Open your Free Edition workspace in a browser and copy its URL host"
step "(the https://<workspace>.cloud.databricks.com part, no trailing slash)."
ask SMELT_DBX_HOST "Workspace host:"
[[ -n "$SMELT_DBX_HOST" ]] || { warn "a workspace host is required."; exit 1; }
write_env SMELT_DBX_HOST "$SMELT_DBX_HOST"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Mint the credential"
say "Free Edition may permit a service principal with an OAuth"
say "machine-to-machine secret; if it does not, a personal access token is"
say "the fallback. This is an empirical fact about the account, not decided"
say "here — try oauth-m2m first in the workspace's Settings > Identity and"
say "access > Service principals; if that surface isn't available, use a"
say "personal access token from your user Settings > Developer instead."
step "Create whichever credential the workspace actually offers."
say "Now capturing it (this hands off to scripts/dbx-key.sh):"
bash scripts/dbx-key.sh
CRED_KIND="$(grep -E '^SMELT_DBX_CRED_KIND=' \
  "${SMELT_DBX_CONFIG_DIR:-$HOME/.config/databricks-smelt-dogfood}/config.env" \
  | tail -n1 | cut -d= -f2)"
write_env SMELT_DBX_CRED_KIND "$CRED_KIND"
say "Credential kind recorded: ${BOLD}${CRED_KIND}${RESET}"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the two schemas and the scoped grants"
say "Nothing beyond ${SCHEMA} and ${ORACLE_SCHEMA} is created or granted —"
say "the credential must not reach any other schema in ${CATALOG}."
bash scripts/dbx-auth.sh
# shellcheck disable=SC1091
source scripts/dbx-dogfood-env.sh >/dev/null

PROVISION_SQL="$(mktemp)"
trap 'rm -f "$PROVISION_SQL"' EXIT

# The GRANT target must be the credential just minted, never a
# workspace/account-wide group — `account users` grants every user in the
# account, defeating the point of a scoped credential.
_dbx_config_dir="${SMELT_DBX_CONFIG_DIR:-$HOME/.config/databricks-smelt-dogfood}"
if [[ "$CRED_KIND" == "oauth-m2m" ]]; then
  GRANT_PRINCIPAL="$(grep -E '^SMELT_DBX_CLIENT_ID=' "${_dbx_config_dir}/config.env" | tail -n1 | cut -d= -f2)"
  [[ -n "$GRANT_PRINCIPAL" ]] || { warn "no SMELT_DBX_CLIENT_ID recorded — cannot scope the grant."; exit 1; }
  cat > "$PROVISION_SQL" <<SQL
CREATE SCHEMA IF NOT EXISTS ${CATALOG}.${SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${CATALOG}.${ORACLE_SCHEMA};
GRANT USE SCHEMA, CREATE TABLE, CREATE VOLUME, SELECT, MODIFY ON SCHEMA ${CATALOG}.${SCHEMA} TO \`${GRANT_PRINCIPAL}\`;
GRANT USE SCHEMA, CREATE TABLE, SELECT, MODIFY ON SCHEMA ${CATALOG}.${ORACLE_SCHEMA} TO \`${GRANT_PRINCIPAL}\`;
SQL
else
  say "PAT credential — it already runs as your own user, so no separate GRANT is needed."
  cat > "$PROVISION_SQL" <<SQL
CREATE SCHEMA IF NOT EXISTS ${CATALOG}.${SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${CATALOG}.${ORACLE_SCHEMA};
SQL
fi
note "The wizard's generated SQL (schema-scoped grants only, nothing catalog-wide):"
cat "$PROVISION_SQL"
say "Creating the two schemas needs CREATE SCHEMA on catalog ${CATALOG}, which a"
say "freshly-scoped credential typically does NOT have yet — Free Edition treats"
say "your own user as workspace admin, so if this fails, run the SQL above"
say "yourself (as your user, e.g. via the Databricks SQL editor) and re-run this"
say "stage; the credential only needs the resulting schema-scoped grants, never"
say "catalog-level rights."
while IFS= read -r stmt; do
  [[ -n "$stmt" ]] || continue
  if ! bash scripts/dbx-query.sh "$stmt" >/dev/null; then
    warn "statement failed: $stmt"
    warn "run the SQL above yourself with an admin-capable credential, then re-run this stage."
    exit 1
  fi
done < <(tr '\n' ' ' < "$PROVISION_SQL" | sed 's/;/\n/g')
say "schemas created, grants applied"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify reachability and out-of-scope refusal"
say "Handing off to scripts/dbx-verify.sh — both legs must pass."
if bash scripts/dbx-verify.sh; then
  say "verification passed"
else
  warn "verification failed — do not proceed until it passes."
  exit 1
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Record the Free Edition quotas"
say "Free Edition carries no bill, so these measured facts stand in for a"
say "budget cap. Find them in the workspace's admin console / docs."
ask DBX_CONCURRENCY "Serverless concurrency limit:"
ask DBX_COLDSTART "Cold-start latency (observed, e.g. '8s'):"
ask DBX_STORAGE "Storage limit:"
ask DBX_IDLE_TIMEOUT "Session idle timeout:"

cat > "$FACTS_SHEET" <<FACTS
# Databricks Free Edition — measured facts

Filled in by scripts/dbx-provision.sh on $(date '+%Y-%m-%d').

| Quota | Value |
|---|---|
| Serverless concurrency | ${DBX_CONCURRENCY} |
| Cold-start latency | ${DBX_COLDSTART} |
| Storage limit | ${DBX_STORAGE} |
| Session idle timeout | ${DBX_IDLE_TIMEOUT} |

## Credential kind chosen

${CRED_KIND} — see scripts/dbx-key.sh and scripts/dbx-auth.sh, which are
credential-agnostic over this choice.
FACTS
say "wrote ${FACTS_SHEET}"

finish
