// Hand-curated. Rule: shown only the emoji, a five-year-old says exactly this word.
// Tier 1: short CVC / common letters. Tier 2: blends and ck/ll/ss. Tier 3: vowel
// digraphs, magic-e, sh/th/ng, r-controlled vowels.
export const WORDS = [
  // tier 1
  { w: 'cat', e: '🐱', tier: 1 },
  { w: 'dog', e: '🐶', tier: 1 },
  { w: 'sun', e: '☀️', tier: 1 },
  { w: 'bed', e: '🛏️', tier: 1 },
  { w: 'pig', e: '🐷', tier: 1 },
  { w: 'bus', e: '🚌', tier: 1 },
  { w: 'egg', e: '🥚', tier: 1 },
  { w: 'hat', e: '🎩', tier: 1 },
  { w: 'cow', e: '🐮', tier: 1 },
  { w: 'bee', e: '🐝', tier: 1 },
  { w: 'ant', e: '🐜', tier: 1 },
  { w: 'fox', e: '🦊', tier: 1 },
  { w: 'bat', e: '🦇', tier: 1 },
  { w: 'rat', e: '🐀', tier: 1 },
  { w: 'car', e: '🚗', tier: 1 },
  { w: 'key', e: '🔑', tier: 1 },
  { w: 'box', e: '📦', tier: 1 },
  { w: 'pen', e: '🖊️', tier: 1 },
  { w: 'bag', e: '👜', tier: 1 },
  { w: 'cap', e: '🧢', tier: 1 },
  { w: 'van', e: '🚐', tier: 1 },
  { w: 'owl', e: '🦉', tier: 1 },
  { w: 'pie', e: '🥧', tier: 1 },
  { w: 'eye', e: '👁️', tier: 1 },
  { w: 'ear', e: '👂', tier: 1 },
  { w: 'leg', e: '🦵', tier: 1 },
  { w: 'log', e: '🪵', tier: 1 },
  { w: 'web', e: '🕸️', tier: 1 },
  { w: 'saw', e: '🪚', tier: 1 },
  { w: 'axe', e: '🪓', tier: 1 },
  { w: 'pin', e: '📌', tier: 1 },
  { w: 'map', e: '🗺️', tier: 1 },
  { w: 'ice', e: '🧊', tier: 1 },
  { w: 'one', e: '1️⃣', tier: 1 },
  { w: 'two', e: '2️⃣', tier: 1 },
  { w: 'six', e: '6️⃣', tier: 1 },
  { w: 'ten', e: '🔟', tier: 1 },
  // tier 2
  { w: 'frog', e: '🐸', tier: 2 },
  { w: 'milk', e: '🥛', tier: 2 },
  { w: 'duck', e: '🦆', tier: 2 },
  { w: 'bell', e: '🔔', tier: 2 },
  { w: 'ball', e: '⚽', tier: 2 },
  { w: 'drum', e: '🥁', tier: 2 },
  { w: 'crab', e: '🦀', tier: 2 },
  { w: 'hand', e: '✋', tier: 2 },
  { w: 'sock', e: '🧦', tier: 2 },
  { w: 'tent', e: '⛺', tier: 2 },
  { w: 'gift', e: '🎁', tier: 2 },
  { w: 'flag', e: '🚩', tier: 2 },
  { w: 'corn', e: '🌽', tier: 2 },
  { w: 'wolf', e: '🐺', tier: 2 },
  { w: 'bath', e: '🛁', tier: 2 },
  { w: 'fish', e: '🐟', tier: 2 },
  { w: 'ship', e: '🚢', tier: 2 },
  { w: 'shoe', e: '👟', tier: 2 },
  { w: 'ring', e: '💍', tier: 2 },
  { w: 'worm', e: '🪱', tier: 2 },
  { w: 'bird', e: '🐦', tier: 2 },
  { w: 'star', e: '⭐', tier: 2 },
  { w: 'fire', e: '🔥', tier: 2 },
  { w: 'four', e: '4️⃣', tier: 2 },
  { w: 'five', e: '5️⃣', tier: 2 },
  { w: 'nine', e: '9️⃣', tier: 2 },
  // tier 3
  { w: 'cake', e: '🍰', tier: 3 },
  { w: 'tree', e: '🌳', tier: 3 },
  { w: 'boat', e: '⛵', tier: 3 },
  { w: 'bear', e: '🐻', tier: 3 },
  { w: 'lion', e: '🦁', tier: 3 },
  { w: 'rain', e: '🌧️', tier: 3 },
  { w: 'leaf', e: '🍃', tier: 3 },
  { w: 'foot', e: '🦶', tier: 3 },
  { w: 'nose', e: '👃', tier: 3 },
  { w: 'door', e: '🚪', tier: 3 },
  { w: 'bone', e: '🦴', tier: 3 },
  { w: 'rose', e: '🌹', tier: 3 },
  { w: 'kite', e: '🪁', tier: 3 },
  { w: 'bike', e: '🚲', tier: 3 },
  { w: 'moon', e: '🌙', tier: 3 },
  { w: 'book', e: '📖', tier: 3 },
  { w: 'goat', e: '🐐', tier: 3 },
  { w: 'deer', e: '🦌', tier: 3 },
  { w: 'seal', e: '🦭', tier: 3 },
  { w: 'pear', e: '🍐', tier: 3 },
  { w: 'rice', e: '🍚', tier: 3 },
  { w: 'coin', e: '🪙', tier: 3 },
  { w: 'dice', e: '🎲', tier: 3 },
  { w: 'wand', e: '🪄', tier: 3 },
  { w: 'fork', e: '🍴', tier: 3 },
  { w: 'hook', e: '🪝', tier: 3 },
  { w: 'bowl', e: '🥣', tier: 3 },
];

export const FRAMES = [
  'I like the {}',
  'Here is a {}',
  'The {} is here',
  'I can see a {}',
  'Look at the {}',
  'I have a {}',
];
